from agents.base_agent import BaseAgent
from tools.gemini_client import GeminiClient
from tools.db_connector import DBConnector
from config.prompts import CHAT_AGENT_PROMPT
import json


class EmailAgent(BaseAgent):
    """
    AI Email Agent — generates personalised email content for customer outreach.
    Handles loan reminders, payment alerts, storage expiry notices, and
    general warehouse communications. All content is generated by the LLM
    using real customer/loan data from the database.
    """

    def __init__(self):
        super().__init__("EmailAgent", "AI-powered email content generation for customer outreach")

    async def process(self, data: dict) -> dict:
        try:
            action     = data.get('action', 'generate')
            role       = data.get('role', 'owner')
            message    = data.get('message', '')

            if action == 'generate':
                return await self._generate_email(data)
            elif action == 'loan_reminder':
                return await self._generate_loan_reminder(data)
            elif action == 'storage_notice':
                return await self._generate_storage_notice(data)
            elif action == 'payment_alert':
                return await self._generate_payment_alert(data)
            elif action == 'bulk_outreach':
                return await self._generate_bulk_outreach(data)
            else:
                return await self._generate_email(data)

        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "message": "Email Agent encountered an error"
            }

    # ------------------------------------------------------------------ #
    #  Internal helpers                                                    #
    # ------------------------------------------------------------------ #

    async def _get_db_context(self, role: str, user_id: str = None) -> dict:
        """Fetch relevant DB data for richer email content."""
        try:
            db = DBConnector()
            ctx = {}
            loans    = await db.get_loans()
            if loans:
                overdue = [l for l in loans if l.get('status') in ('overdue', 'defaulted')]
                pending = [l for l in loans if l.get('status') == 'approved']
                ctx['overdue_loans']  = len(overdue)
                ctx['pending_loans']  = len(pending)
                ctx['total_loans']    = len(loans)
                ctx['overdue_sample'] = overdue[:3]
            inventory = await db.get_inventory()
            if inventory:
                ctx['total_stock_bags'] = sum(i.get('totalBags', 0) for i in inventory)
            return ctx
        except Exception:
            return {}

    async def _generate_email(self, data: dict) -> dict:
        """Generic email generation from a prompt."""
        purpose    = data.get('purpose', 'general communication')
        customer   = data.get('customerName', 'Valued Customer')
        extra_ctx  = data.get('extraContext', '')

        prompt = f"""You are an AI assistant helping a warehouse manager draft a professional email.

Purpose: {purpose}
Customer Name: {customer}
Additional Context: {extra_ctx}

Write a professional, friendly email. Include:
- A clear subject line (prefix with "Subject: ")
- A proper greeting
- A concise body with the key message
- A polite closing

Use formal but warm language suitable for a grain warehouse business."""

        raw = await GeminiClient.generate_text(prompt, CHAT_AGENT_PROMPT)

        # Split subject from body if the LLM included it
        subject, body = 'Message from Warehouse Management System', raw
        for line in raw.split('\n'):
            if line.lower().startswith('subject:'):
                subject = line.split(':', 1)[1].strip()
                body    = raw[raw.find('\n') + 1:].strip()
                break

        return {
            "success":   True,
            "agent":     "email",
            "action":    "generate",
            "data": {
                "subject": subject,
                "body":    body,
                "reply":   f"Email generated:\n\n**Subject:** {subject}\n\n{body}",
            }
        }

    async def _generate_loan_reminder(self, data: dict) -> dict:
        """Generate a personalised loan repayment reminder."""
        customer_name  = data.get('customerName', 'Customer')
        loan_amount    = data.get('loanAmount', 0)
        due_date       = data.get('dueDate', 'as soon as possible')
        days_overdue   = data.get('daysOverdue', 0)
        grain_type     = data.get('grainType', '')
        loan_id        = data.get('loanId', '')

        urgency = "urgent" if days_overdue > 30 else "friendly"

        prompt = f"""You are an AI assistant for a grain warehouse. Write a {urgency} loan repayment reminder email.

Customer: {customer_name}
Outstanding Loan Amount: ₹{loan_amount:,.0f}
Due Date: {due_date}
Days Overdue: {days_overdue} days
Grain Collateral: {grain_type}
Loan Reference: {loan_id}

Write a professional email reminder. Include:
- Subject line (prefix "Subject: ")
- Polite but firm reminder of the outstanding amount
- Clear due date and payment instructions
- Mention of the grain collateral if applicable
- Contact details for queries
- Use ₹ for currency and Indian numbering (lakhs/crores)

{'Use a firm tone emphasising urgency and possible consequences.' if days_overdue > 30 else 'Use a polite, friendly tone.'}"""

        raw = await GeminiClient.generate_text(prompt, CHAT_AGENT_PROMPT)

        subject = f"Loan Repayment Reminder — ₹{loan_amount:,.0f} Due"
        body    = raw
        for line in raw.split('\n'):
            if line.lower().startswith('subject:'):
                subject = line.split(':', 1)[1].strip()
                body    = '\n'.join(raw.split('\n')[1:]).strip()
                break

        return {
            "success": True,
            "agent":   "email",
            "action":  "loan_reminder",
            "data": {
                "subject":     subject,
                "body":        body,
                "reply":       f"Loan reminder email generated for {customer_name}:\n\n**Subject:** {subject}\n\n{body}",
                "customerName": customer_name,
                "loanAmount":   loan_amount,
            }
        }

    async def _generate_storage_notice(self, data: dict) -> dict:
        """Generate a storage expiry / collection notice."""
        customer_name  = data.get('customerName', 'Customer')
        grain_type     = data.get('grainType', 'grain')
        bags           = data.get('bags', 0)
        stored_since   = data.get('storedSince', '')
        expiry_date    = data.get('expiryDate', '')
        storage_charges = data.get('storageCharges', 0)

        prompt = f"""Write a professional storage notice email for a grain warehouse.

Customer: {customer_name}
Grain Type: {grain_type}
Quantity: {bags} bags
Stored Since: {stored_since}
Storage Expiry: {expiry_date}
Pending Storage Charges: ₹{storage_charges:,.0f}

Write a polite email informing the customer their storage period is ending. Include:
- Subject line (prefix "Subject: ")
- Details of their stored grain
- Storage expiry date and pending charges
- Request to collect or renew storage
- Contact information"""

        raw = await GeminiClient.generate_text(prompt, CHAT_AGENT_PROMPT)

        subject = f"Storage Notice — {grain_type.title()} Collection Required"
        body    = raw
        for line in raw.split('\n'):
            if line.lower().startswith('subject:'):
                subject = line.split(':', 1)[1].strip()
                body    = '\n'.join(raw.split('\n')[1:]).strip()
                break

        return {
            "success": True,
            "agent":   "email",
            "action":  "storage_notice",
            "data": {
                "subject": subject,
                "body":    body,
                "reply":   f"Storage notice generated for {customer_name}:\n\n**Subject:** {subject}\n\n{body}",
            }
        }

    async def _generate_payment_alert(self, data: dict) -> dict:
        """Generate a payment received / confirmation email."""
        customer_name  = data.get('customerName', 'Customer')
        amount         = data.get('amount', 0)
        payment_mode   = data.get('paymentMode', 'bank transfer')
        reference      = data.get('reference', '')

        prompt = f"""Write a payment confirmation email for a grain warehouse.

Customer: {customer_name}
Amount Received: ₹{amount:,.0f}
Payment Mode: {payment_mode}
Reference: {reference}

Write a warm, professional confirmation email. Include:
- Subject line (prefix "Subject: ")
- Acknowledgement of payment received
- Payment details (amount, mode, reference)
- Updated account status
- Thank the customer"""

        raw = await GeminiClient.generate_text(prompt, CHAT_AGENT_PROMPT)

        subject = f"Payment Confirmation — ₹{amount:,.0f} Received"
        body    = raw
        for line in raw.split('\n'):
            if line.lower().startswith('subject:'):
                subject = line.split(':', 1)[1].strip()
                body    = '\n'.join(raw.split('\n')[1:]).strip()
                break

        return {
            "success": True,
            "agent":   "email",
            "action":  "payment_alert",
            "data": {
                "subject": subject,
                "body":    body,
                "reply":   f"Payment confirmation generated for {customer_name}:\n\n**Subject:** {subject}\n\n{body}",
            }
        }

    async def _generate_bulk_outreach(self, data: dict) -> dict:
        """Generate bulk email templates for all customers with overdue loans."""
        ctx  = await self._get_db_context(data.get('role', 'owner'))
        tone = data.get('tone', 'friendly')

        prompt = f"""You are an AI assistant for a grain warehouse. Generate a bulk email template 
for customers with overdue loans.

Warehouse Stats:
- Total Loans: {ctx.get('total_loans', 'N/A')}
- Overdue Loans: {ctx.get('overdue_loans', 'N/A')}
- Pending Loans: {ctx.get('pending_loans', 'N/A')}

Tone: {tone}

Write a professional bulk email template with [CUSTOMER_NAME] and [LOAN_AMOUNT] as placeholders.
Include:
- Subject line (prefix "Subject: ")
- Warm greeting with placeholder
- Clear repayment request
- Payment options available
- Deadline reminder
- Contact details"""

        raw = await GeminiClient.generate_text(prompt, CHAT_AGENT_PROMPT)

        subject = "Important: Loan Repayment Required — Warehouse Management System"
        body    = raw
        for line in raw.split('\n'):
            if line.lower().startswith('subject:'):
                subject = line.split(':', 1)[1].strip()
                body    = '\n'.join(raw.split('\n')[1:]).strip()
                break

        return {
            "success": True,
            "agent":   "email",
            "action":  "bulk_outreach",
            "data": {
                "subject":      subject,
                "body":         body,
                "overdueCount": ctx.get('overdue_loans', 0),
                "reply":        (
                    f"Bulk email template generated.\n"
                    f"- Overdue loans to contact: {ctx.get('overdue_loans', 0)}\n\n"
                    f"**Subject:** {subject}\n\n{body}"
                ),
            }
        }
